Разметка страницы каталога
htmlacademy-adaptive/1326685-cat-energy-21 pull request #4
Opened 2020-11-22 10:27 UTC by iAl1ve

2020-11-22 16:57 UTC, andreysgra requested changes

2020-11-22 16:57 UTC, andreysgra commented on source/catalog.html
> +          </li>
```suggestion
          <li class="header__nav-item">
            <a class="header__nav-link header__nav-link--active">Каталог продукции</a>
          </li>
          <li class="header__nav-item">
            <a class="header__nav-link" href="form.html">Подбор программы</a>
          </li>
```

2020-11-22 16:57 UTC, andreysgra commented on source/catalog.html
> +          </li>
Здесь совершенно другой блок, а список должен объединять одинаковые сущности (у нас это карточки товара).

Советую сделать разметку без списка.

2020-11-22 16:57 UTC, andreysgra commented on source/catalog.html
> +              <a class="card__link" href="#!">
Думаю, что "Показать еще 100500 товаров" это просто надпись и ссылка здесь не нужна (ссылка есть ниже).

2020-11-22 21:02 UTC, iAl1ve commented on source/catalog.html
> +              <a class="card__link" href="#!">
Думал как удобней. Но хорошо, лучше следовать по ТЗ.

2020-11-22 21:04 UTC, iAl1ve commented on source/catalog.html
> +          </li>
Насчет другой сущности полностью согласен. Как я понимаю, это также лучше и удобней делать для реализации в ТЗ пункта 6.3 ( https://up.htmlacademy.ru/adaptive/21/project/cat-energy#cat-energy-6-3 ) функционала добавления новых карточек?

2020-11-22 21:04 UTC, iAl1ve commented
Спасибо за замечания! Поправил.

2020-11-23 06:53 UTC, andreysgra commented on source/catalog.html
> +          </li>
Да, верно.

2020-11-23 06:54 UTC, merged